/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.gui.presentacion.Administrador;

import client.gui.Roles.JfrmLogin;
import java.awt.BorderLayout;
import java.io.IOException;

import client.ClientInstance;
import java.util.concurrent.TimeUnit;
import share.VanityConsole;


/**
 *
 * @author jhose
 */

 @SuppressWarnings("unused")
public class JfrmPrincipalAdmin extends javax.swing.JFrame {

	ClientInstance clientInstance = new ClientInstance();
	String response;
    /**
     * Creates new form JfrmPrincipalAdmin
     */
    public JfrmPrincipalAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnOpciones = new javax.swing.ButtonGroup();
        btnOpciones.add(jrbAgencias);
        btnOpciones.add(jrbGarajes);
        btnOpciones.add(jrbAutomovil);
        btnOpciones.add(jrbReservas);
        btnOpciones.add(jrbClientes);
        btnOpciones.add(jrbIngresos);
        btnOpciones.add(jrbCombustible);
		try {
			clientInstance.connect("localhost", 6969);
			clientInstance.sendMessage("001 CONEXION ADMINISTRADOR");
			response = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
			VanityConsole.shout(response);

		} catch (IOException e) {
	    	new javax.swing.JOptionPane().showMessageDialog(this, "Error al conectar con el servidor: " + e.getMessage(), "Error de conexión", javax.swing.JOptionPane.ERROR_MESSAGE);
			System.exit(1);

		} catch (InterruptedException e) {
			    	new javax.swing.JOptionPane().showMessageDialog(this, "Error de tiempo de espera: " + e.getMessage(), "Error de conexión", javax.swing.JOptionPane.ERROR_MESSAGE);
			System.exit(1);
		}
    }

    private void cargarPanel(javax.swing.JPanel panel) {
        panel.setSize(1400, 899);
        panel.setLocation(0, 0);
        panContenido.removeAll();
        panContenido.add(panel, BorderLayout.CENTER);
        panContenido.revalidate();
        panContenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        @SuppressWarnings("Convert2Lambda")
    private void initComponents() {

        btnOpciones = new javax.swing.ButtonGroup();
        panContenido = new javax.swing.JPanel();
        jrbAgencias = new javax.swing.JRadioButton();
        lblFunciones = new javax.swing.JLabel();
        jrbAutomovil = new javax.swing.JRadioButton();
        jrbGarajes = new javax.swing.JRadioButton();
        jrbReservas = new javax.swing.JRadioButton();
        jrbClientes = new javax.swing.JRadioButton();
        btnSalir = new javax.swing.JButton();
        jrbIngresos = new javax.swing.JRadioButton();
        lblReportes = new javax.swing.JLabel();
        jrbCombustible = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        panContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );

        jrbAgencias.setText("Agencias");
        jrbAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAgenciasActionPerformed(evt);
            }
        });

        lblFunciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFunciones.setText("Funciones");

        jrbAutomovil.setText("Automovil");
        jrbAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAutomovilActionPerformed(evt);
            }
        });

        jrbGarajes.setText("Garajes");
        jrbGarajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGarajesActionPerformed(evt);
            }
        });

        jrbReservas.setText("Reservas");
        jrbReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbReservasActionPerformed(evt);
            }
        });

        jrbClientes.setText("Clientes");
        jrbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbClientesActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(8, 156, 12));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jrbIngresos.setText("Ingresos");
        jrbIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbIngresosActionPerformed(evt);
            }
        });

        lblReportes.setText("Reportes");

        jrbCombustible.setText("Combustible");
        jrbCombustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCombustibleActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblFunciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbAgencias)
                                    .addComponent(jrbAutomovil)
                                    .addComponent(jrbGarajes)
                                    .addComponent(jrbReservas)
                                    .addComponent(jrbClientes)
                                    .addComponent(lblReportes))
                                .addGap(35, 35, 35))
                            .addComponent(btnSalir)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbCombustible)
                            .addComponent(jrbIngresos))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(panContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lblFunciones)
                .addGap(76, 76, 76)
                .addComponent(jrbAgencias)
                .addGap(18, 18, 18)
                .addComponent(jrbGarajes)
                .addGap(18, 18, 18)
                .addComponent(jrbAutomovil)
                .addGap(18, 18, 18)
                .addComponent(jrbClientes)
                .addGap(18, 18, 18)
                .addComponent(jrbReservas)
                .addGap(23, 23, 23)
                .addComponent(lblReportes)
                .addGap(18, 18, 18)
                .addComponent(jrbIngresos)
                .addGap(18, 18, 18)
                .addComponent(jrbCombustible)
                .addGap(62, 62, 62)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAgenciasActionPerformed
        PanGestionAgenciasAdministrador panel = new PanGestionAgenciasAdministrador(clientInstance);
        cargarPanel(panel);
    }//GEN-LAST:event_jrbAgenciasActionPerformed

    private void jrbGarajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGarajesActionPerformed
        PanGestionGarajeAdministrador panel = new PanGestionGarajeAdministrador(clientInstance);
        cargarPanel(panel);
    }//GEN-LAST:event_jrbGarajesActionPerformed

    private void jrbAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAutomovilActionPerformed
        PanGestionAutomovilesAdministrador panel = new PanGestionAutomovilesAdministrador(clientInstance);
        cargarPanel(panel);
    }//GEN-LAST:event_jrbAutomovilActionPerformed

    private void jrbReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbReservasActionPerformed
        PanGestionReservasAdministrador panel = new PanGestionReservasAdministrador(clientInstance);
        cargarPanel(panel);
    }//GEN-LAST:event_jrbReservasActionPerformed

    private void jrbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbClientesActionPerformed
        PanGestionClientesAdministrador panel = new PanGestionClientesAdministrador(clientInstance);
        cargarPanel(panel);
    }//GEN-LAST:event_jrbClientesActionPerformed

    private void jrbIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbIngresosActionPerformed
        PanReportesIngresosAdministrador panel = new PanReportesIngresosAdministrador(clientInstance);
        cargarPanel(panel);
    }//GEN-LAST:event_jrbIngresosActionPerformed

    private void jrbCombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCombustibleActionPerformed
        PanReportesCombustibleAdministrador panel = new PanReportesCombustibleAdministrador(clientInstance);
        cargarPanel(panel);
    }//GEN-LAST:event_jrbCombustibleActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        JfrmLogin login = new JfrmLogin();
        login.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            //</editor-fold>
            
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JfrmPrincipalAdmin().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnOpciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jrbAgencias;
    private javax.swing.JRadioButton jrbAutomovil;
    private javax.swing.JRadioButton jrbClientes;
    private javax.swing.JRadioButton jrbCombustible;
    private javax.swing.JRadioButton jrbGarajes;
    private javax.swing.JRadioButton jrbIngresos;
    private javax.swing.JRadioButton jrbReservas;
    private javax.swing.JLabel lblFunciones;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JPanel panContenido;
    // End of variables declaration//GEN-END:variables
}
