/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client.gui.presentacion.Administrador;

import client.ClientInstance;
import client.RequestHandler;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author jhose
 */
public class PanGestionAutomovilesAdministrador extends javax.swing.JPanel {
	ClientInstance clientInstance;

    /**
     * Creates new form PanGestionAutomovilesAdministrador
     */
    public PanGestionAutomovilesAdministrador(ClientInstance clientInstance) {
        initComponents();
		this.clientInstance = clientInstance;
		populateTable();
    }

	private void populateTable(){
		// Clear the table before populating it
		javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblGestionAutomovil.getModel();
		model.setRowCount(0); 
		clientInstance.sendMessage("104");
		String raw;
		try {
			raw = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
			raw = raw.substring(3);
		} catch (InterruptedException e) {
			raw = "|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|";
		}
		ArrayList<String> rows = RequestHandler.superArrayReconstructor(raw);
		
		for (String i : rows) {
			ArrayList<String> row = RequestHandler.arrayReconstructor(i);
			if (row.size() == 6) {
				model = (javax.swing.table.DefaultTableModel) tblGestionAutomovil.getModel();
				model.addRow(new Object[]{row.get(0), row.get(1), row.get(2), row.get(3), row.get(4), row.get(5)});
			} else {
				System.out.println("Error: Row does not contain exactly 6 elements. "+
						"Received: " + row.size() + " elements." + i);
			}
		}
	}

	private void populateTableWithData(String msg){
		// Clear the table before populating it
		javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblGestionAutomovil.getModel();
		model.setRowCount(0); 
		clientInstance.sendMessage(msg);
		String raw;
		try {
			raw = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
			raw = raw.substring(3);
		} catch (InterruptedException e) {
			raw = "|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|";
		}
		ArrayList<String> rows = RequestHandler.superArrayReconstructor(raw);
		
		for (String i : rows) {
			ArrayList<String> row = RequestHandler.arrayReconstructor(i);
			if (row.size() == 6) {
				model = (javax.swing.table.DefaultTableModel) tblGestionAutomovil.getModel();
				model.addRow(new Object[]{row.get(0), row.get(1), row.get(2), row.get(3), row.get(4), row.get(5)});
			} else {
				System.out.println("Error: Row does not contain exactly 6 elements. "+
						"Received: " + row.size() + " elements." + i);
			}
		}
	}

	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGestionAutomovil = new javax.swing.JTable();
        lblPlaca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblGaraje = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtGaraje = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblBuscarPlaca = new javax.swing.JLabel();
        lblBuscarMarca = new javax.swing.JLabel();
        txtBuscarPlaca = new javax.swing.JTextField();
        txtBuscarMarca = new javax.swing.JTextField();
        btnConsultarMarca = new javax.swing.JButton();
        btnConsultarPlaca = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tblGestionAutomovil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Placa", "Modelo", "Color", "Marca", "Estado", "Garaje"
            }
        ));
        jScrollPane1.setViewportView(tblGestionAutomovil);

        lblPlaca.setText("Placa");

        lblModelo.setText("Modelo");

        lblColor.setText("Color");

        lblMarca.setText("Marca");

        lblEstado.setText("Estado");

        lblGaraje.setText("Garaje");

        txtColor.setToolTipText("");
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(8, 156, 12));
        //btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Registrar.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
		btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnRegistrarMouseClicked(evt);
			}
		});
        btnActualizar.setBackground(new java.awt.Color(8, 156, 12));
        //btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
		btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnActualizarMouseClicked(evt);
			}
		});
        btnEliminar.setBackground(new java.awt.Color(8, 156, 12));
        //btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/elminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
		btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnEliminarMouseClicked(evt);
			}
		});
        jButton4.setBackground(new java.awt.Color(8, 156, 12));
        //jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        jButton4.setText("Refrescar");
		jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton4MouseClicked(evt);
			}
		});

        lblBuscarPlaca.setText("Buscar por placa");

        lblBuscarMarca.setText("Buscar por marca");

        btnConsultarMarca.setBackground(new java.awt.Color(8, 156, 12));
        //btnConsultarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Buscar.png"))); // NOI18N
		btnConsultarMarca.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnConsultarMarcaMouseClicked(evt);
			}
		});
        btnConsultarPlaca.setBackground(new java.awt.Color(8, 156, 12));
        //btnConsultarPlaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Buscar.png"))); // NOI18N
		btnConsultarPlaca.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnConsultarPlacaMouseClicked(evt);
			}
		});
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblPlaca))
                    .addComponent(lblColor)
                    .addComponent(lblModelo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEstado)
                                    .addComponent(lblMarca)
                                    .addComponent(lblGaraje))
                                .addGap(155, 155, 155)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPlaca)
                                    .addComponent(txtModelo)
                                    .addComponent(txtColor)
                                    .addComponent(txtMarca)
                                    .addComponent(txtEstado)
                                    .addComponent(txtGaraje, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBuscarPlaca)
                                    .addComponent(lblBuscarMarca))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBuscarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnConsultarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConsultarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(43, 43, 43)
                                .addComponent(btnRegistrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlaca)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModelo)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblColor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMarca))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGaraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGaraje))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(btnRegistrar)
                            .addComponent(btnActualizar)
                            .addComponent(btnEliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblBuscarPlaca)
                                .addGap(23, 23, 23)
                                .addComponent(lblBuscarMarca))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConsultarPlaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBuscarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConsultarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(206, 206, 206))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed


	private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked	
		String placa = txtPlaca.getText();
		String modelo = txtModelo.getText();
		String color = txtColor.getText();
		String marca = txtMarca.getText();
		String estado = txtEstado.getText();
		String garaje = txtGaraje.getText();
		if (placa.isEmpty() || modelo.isEmpty() || color.isEmpty() || marca.isEmpty() || estado.isEmpty() || garaje.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "All fields must be filled out.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
			System.out.println("Error: All fields must be filled out.");
			return;
		}

		clientInstance.sendMessage("305 " + placa + "|" + modelo + "|" + color + "|" + marca + "|" + estado + "|" + garaje);
		String response;
		try {
			response = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
		} catch (InterruptedException e) {
			response ="801" + e.getMessage();
		}
		if (response.equals("800")) {
			System.out.println("Garage registered successfully.");
			populateTable();
		} else {
			System.out.println("Error registering garaje: " + response);
		}
	}//GEN-LAST:event_btnRegistrarMouseClicked

	private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
		populateTable();
	}//GEN-LAST:event_jButton4MouseClicked

	private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
		String agencia = txtPlaca.getText();

		if (agencia.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "All fields must be filled out.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
			System.out.println("Error: All fields must be filled out.");
			return;
		}
		clientInstance.sendMessage("403 |" + agencia+"|");

		populateTable();
	}

	private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
		String placa = txtPlaca.getText();
		String modelo = txtModelo.getText();
		String color = txtColor.getText();
		String marca = txtMarca.getText();
		String estado = txtEstado.getText();
		String garaje = txtGaraje.getText();

		if (placa.isEmpty() || modelo.isEmpty() || color.isEmpty() || marca.isEmpty() || estado.isEmpty() || garaje.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "All fields must be filled out.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
			System.out.println("Error: All fields must be filled out.");
			return;
		}

		clientInstance.sendMessage("310 " + "|" + modelo + "|" + color + "|" + marca + "|" + estado + "|" + garaje+ "|" + placa);
		String response;
		try {
			response = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
		} catch (InterruptedException e) {
			response = "801" + e.getMessage();
		}
		if (response.equals("800")) {
			System.out.println("Agency updated successfully.");
			populateTable();
		} else {
			System.out.println("Error updating agency: " + response);
		}
	}//GEN-LAST:event_btnActualizarMouseClicked

	private void btnConsultarMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMarcaMouseClicked
		String marca = txtBuscarMarca.getText();
		if (marca.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "Please enter a marca to search.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
			System.out.println("Error: Please enter a marca to search.");
			return;
		}
		String msg = "110 " + marca;
		populateTableWithData(msg);
	}//GEN-LAST:event_btnConsultarMarcaMouseClicked
	private void btnConsultarPlacaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarPlacaMouseClicked
		String placa = txtBuscarPlaca.getText();
		if (placa.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "Please enter a placa to search.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
			System.out.println("Error: Please enter a placa to search.");
			return;
		}
		String msg = "111 " + placa;
		populateTableWithData(msg);
	}//GEN-LAST:event_btnConsultarPlacaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultarMarca;
    private javax.swing.JButton btnConsultarPlaca;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarMarca;
    private javax.swing.JLabel lblBuscarPlaca;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblGaraje;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JTable tblGestionAutomovil;
    private javax.swing.JTextField txtBuscarMarca;
    private javax.swing.JTextField txtBuscarPlaca;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtGaraje;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
