/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client.gui.presentacion.Administrador;

import java.util.ArrayList;
import java.util.concurrent.TimeUnit;

import client.ClientInstance;
import client.RequestHandler;

/**
 *
 * @author jhose
 */
public class PanGestionGarajeAdministrador extends javax.swing.JPanel {
	ClientInstance clientInstance;

    /**
     * Creates new form PanGestionGarajeAdministrador
     */
    public PanGestionGarajeAdministrador(ClientInstance clientInstance) {
        initComponents();
		this.clientInstance = clientInstance;
		populateTable();
    }
private void populateTable(){
		// Clear the table before populating it
		javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblGestionGaraje.getModel();
		model.setRowCount(0); 
		clientInstance.sendMessage("102");
		String raw;
		try {
			raw = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
			raw = raw.substring(3);
		} catch (InterruptedException e) {
			raw = "|Error receiving data|Error receiving data|Error receiving data|";
		}
		ArrayList<String> rows = RequestHandler.superArrayReconstructor(raw);
		
		for (String i : rows) {
			ArrayList<String> row = RequestHandler.arrayReconstructor(i);
			if (row.size() == 3) {
				model = (javax.swing.table.DefaultTableModel) tblGestionGaraje.getModel();
				model.addRow(new Object[]{row.get(0), row.get(1), row.get(2)});
			} else {
				System.out.println("Error: Row does not contain exactly 3 elements. "+
						"Received: " + row.size() + " elements." + i);
			}
		}
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGaraje = new javax.swing.JLabel();
        lblBuscarGaraje = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtBuscarNombre = new javax.swing.JTextField();
        lblUbicacion = new javax.swing.JLabel();
        txtBuscarAgencia = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtGaraje = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGestionGaraje = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblBuscarNombre = new javax.swing.JLabel();
        btnConsultarNombre = new javax.swing.JButton();
        btnConsultarGaraje = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblGaraje.setText("Garaje");

        lblBuscarGaraje.setText("Buscar por garaje");

        lblNombre.setText("Nombre");

        lblUbicacion.setText("Ubicacion");

        txtGaraje.setToolTipText("");
        txtGaraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGarajeActionPerformed(evt);
            }
        });

        txtUbicacion.setToolTipText("");

        btnRegistrar.setBackground(new java.awt.Color(8, 156, 12));
        //btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Registrar.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
		btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnRegistrarMouseClicked(evt);
			}
		});

        tblGestionGaraje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Garaje", "Nombre", "Ubicacion"
            }
        ));
        jScrollPane1.setViewportView(tblGestionGaraje);

        btnActualizar.setBackground(new java.awt.Color(8, 156, 12));
        //btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
				btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnActualizarMouseClicked(evt);
			}
		});

        btnEliminar.setBackground(new java.awt.Color(8, 156, 12));
        //btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/elminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
		btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnEliminarMouseClicked(evt);
			}
		});

        jButton4.setBackground(new java.awt.Color(8, 156, 12));
        //jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        jButton4.setText("Refrescar");
		jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton4MouseClicked(evt);
			}
		});

        lblBuscarNombre.setText("Buscar por nombre");

        btnConsultarNombre.setBackground(new java.awt.Color(8, 156, 12));
        //btnConsultarNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Buscar.png"))); // NOI18N

        btnConsultarGaraje.setBackground(new java.awt.Color(8, 156, 12));
        //btnConsultarGaraje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Buscar.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGaraje)
                            .addComponent(lblNombre)
                            .addComponent(lblUbicacion))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGaraje, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(lblBuscarGaraje)
                            .addComponent(lblBuscarNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnConsultarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtBuscarAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnConsultarGaraje, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGaraje)
                            .addComponent(txtGaraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUbicacion))
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(btnActualizar)
                            .addComponent(btnEliminar)
                            .addComponent(jButton4))
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBuscarNombre)
                            .addComponent(txtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultarGaraje, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBuscarGaraje))))
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGarajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGarajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGarajeActionPerformed

	private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked	
		String nombre = txtNombre.getText();
		String direccion = txtUbicacion.getText();

		if (nombre.isEmpty() || direccion.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "All fields must be filled out.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
			System.out.println("Error: All fields must be filled out.");
			return;
		}

		clientInstance.sendMessage("302 " + nombre + "|" + direccion);
		String response;
		try {
			response = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
		} catch (InterruptedException e) {
			response ="801" + e.getMessage();
		}
		if (response.equals("800")) {
			System.out.println("Agency registered successfully.");
			populateTable();
		} else {
			System.out.println("Error registering agency: " + response);
		}
	}//GEN-LAST:event_btnRegistrarMouseClicked

	private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
		populateTable();
	}//GEN-LAST:event_jButton4MouseClicked

	private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
		String agencia = txtGaraje.getText();

		if (agencia.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "All fields must be filled out.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
			System.out.println("Error: All fields must be filled out.");
			return;
		}
		clientInstance.sendMessage("402 |" + agencia+"|");

		populateTable();
	}

	private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
		String agencia = txtGaraje.getText();
		String nombre = txtNombre.getText();
		String direccion = txtUbicacion.getText();
		if (agencia.isEmpty() || nombre.isEmpty() || direccion.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "All fields must be filled out.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
			System.out.println("Error: All fields must be filled out.");
			return;
		}
		clientInstance.sendMessage("309 " + agencia + "|" + nombre + "|" + direccion);
		String response;
		try {
			response = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
		} catch (InterruptedException e) {
			response = "801" + e.getMessage();
		}
		if (response.equals("800")) {
			System.out.println("Agency updated successfully.");
			populateTable();
		} else {
			System.out.println("Error updating agency: " + response);
		}
	}//GEN-LAST:event_btnActualizarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultarGaraje;
    private javax.swing.JButton btnConsultarNombre;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarGaraje;
    private javax.swing.JLabel lblBuscarNombre;
    private javax.swing.JLabel lblGaraje;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JTable tblGestionGaraje;
    private javax.swing.JTextField txtBuscarAgencia;
    private javax.swing.JTextField txtBuscarNombre;
    private javax.swing.JTextField txtGaraje;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
