/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client.gui.presentacion.Administrador;

import client.ClientInstance;

/**
 *
 * @author jhose
 */
public class PanReportesIngresosAdministrador extends javax.swing.JPanel {
	ClientInstance clientInstance;

    /**
     * Creates new form PanReportesIngresosAdministrador
     */
    public PanReportesIngresosAdministrador(ClientInstance clientInstance) {
        initComponents();
		this.clientInstance = clientInstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporteMes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReporteAgencia = new javax.swing.JTable();
        btnDescargarReporteAgencia = new javax.swing.JButton();
        btnDescargarReporteMes = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tblReporteMes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mes", "Ingresos totales"
            }
        ));
        jScrollPane1.setViewportView(tblReporteMes);

        tblReporteAgencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Agencia", "Ingresos totales"
            }
        ));
        jScrollPane2.setViewportView(tblReporteAgencia);

        btnDescargarReporteAgencia.setBackground(new java.awt.Color(8, 156, 12));
        //btnDescargarReporteAgencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/descarga.png"))); // NOI18N
        btnDescargarReporteAgencia.setText("Descargar reporte agencia");

        btnDescargarReporteMes.setBackground(new java.awt.Color(8, 156, 12));
        //btnDescargarReporteMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/descarga.png"))); // NOI18N
        btnDescargarReporteMes.setText("Descargar reporte mes");
        btnDescargarReporteMes.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(btnDescargarReporteAgencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDescargarReporteMes)
                .addGap(324, 324, 324))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDescargarReporteAgencia)
                    .addComponent(btnDescargarReporteMes))
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescargarReporteAgencia;
    private javax.swing.JButton btnDescargarReporteMes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblReporteAgencia;
    private javax.swing.JTable tblReporteMes;
    // End of variables declaration//GEN-END:variables
}
