/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client.gui.presentacion.Administrador;

import client.ClientInstance;
import client.RequestHandler;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author jhose
 */
public class PanReportesIngresosAdministrador extends javax.swing.JPanel {
	ClientInstance clientInstance;

    /**
     * Creates new form PanReportesIngresosAdministrador
     */
    public PanReportesIngresosAdministrador(ClientInstance clientInstance) {
        initComponents();
		this.clientInstance = clientInstance;
    }

	private void populateTableMonthWithData(String msg){
		// Clear the table before populating it
		javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblReporteMes.getModel();
		model.setRowCount(0); 
		clientInstance.sendMessage(msg);
		String raw;
		try {
			raw = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
			raw = raw.substring(3);
		} catch (InterruptedException e) {
			raw = "|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|";
		}
		ArrayList<String> rows = RequestHandler.superArrayReconstructor(raw);
		
		for (String i : rows) {
			ArrayList<String> row = RequestHandler.arrayReconstructor(i);
			if (row.size() == 2) {
				model = (javax.swing.table.DefaultTableModel) tblReporteMes.getModel();
				model.addRow(new Object[]{row.get(0), row.get(1)});
			} else {
				System.out.println("Error: Row does not contain exactly 8 elements. "+
						"Received: " + row.size() + " elements." + i);
			}
		}
	}

	private void populateTableAgencyWithData(String msg){
		// Clear the table before populating it
		javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblReporteAgencia.getModel();
		model.setRowCount(0); 
		clientInstance.sendMessage(msg);
		String raw;
		try {
			raw = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
			raw = raw.substring(3);
		} catch (InterruptedException e) {
			raw = "|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|";
		}
		ArrayList<String> rows = RequestHandler.superArrayReconstructor(raw);
		
		for (String i : rows) {
			ArrayList<String> row = RequestHandler.arrayReconstructor(i);
			if (row.size() == 2) {
				model = (javax.swing.table.DefaultTableModel) tblReporteAgencia.getModel();
				model.addRow(new Object[]{row.get(0), row.get(1)});
			} else {
				System.out.println("Error: Row does not contain exactly 8 elements. "+
						"Received: " + row.size() + " elements." + i);
			}
		}
	}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporteMes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReporteAgencia = new javax.swing.JTable();
        btnDescargarReporteAgencia = new javax.swing.JButton();
        btnDescargarReporteMes = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tblReporteMes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mes", "Ingresos totales"
            }
        ));
        jScrollPane1.setViewportView(tblReporteMes);

        tblReporteAgencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Agencia", "Ingresos totales"
            }
        ));
        jScrollPane2.setViewportView(tblReporteAgencia);

        btnDescargarReporteAgencia.setBackground(new java.awt.Color(8, 156, 12));
        //btnDescargarReporteAgencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/descarga.png"))); // NOI18N
        btnDescargarReporteAgencia.setText("Generar reporte agencia");
		btnDescargarReporteAgencia.setToolTipText("");
		btnDescargarReporteAgencia.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDescargarReporteAgenciaActionPerformed(evt);
			}
		});

        btnDescargarReporteMes.setBackground(new java.awt.Color(8, 156, 12));
        //btnDescargarReporteMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/descarga.png"))); // NOI18N
        btnDescargarReporteMes.setText("Generar reporte mes");
        btnDescargarReporteMes.setToolTipText("");
		btnDescargarReporteMes.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDescargarReporteMesActionPerformed(evt);
			}
		});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(btnDescargarReporteAgencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDescargarReporteMes)
                .addGap(324, 324, 324))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDescargarReporteAgencia)
                    .addComponent(btnDescargarReporteMes))
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void btnDescargarReporteMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarReporteMesActionPerformed
		
		populateTableMonthWithData("501");
	}//GEN-LAST:event_btnDescargarReporteMesActionPerformed

	private void btnDescargarReporteAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarReporteAgenciaActionPerformed
		
		populateTableAgencyWithData("502");
	}//GEN-LAST:event_btnDescargarReporteAgenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescargarReporteAgencia;
    private javax.swing.JButton btnDescargarReporteMes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblReporteAgencia;
    private javax.swing.JTable tblReporteMes;
    // End of variables declaration//GEN-END:variables
}
