/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client.gui.presentacion.Empleado;


import client.ClientInstance;
import client.RequestHandler;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author jhose
 */
public class PanGestionReservaEmpleado extends javax.swing.JPanel {

	ClientInstance clientInstance;
    /**
     * Creates new form PanGestionReservaEmpleado
     */
    public PanGestionReservaEmpleado(ClientInstance clientInstance) {
		this.clientInstance = clientInstance;
        initComponents();
		populateTable();
    }

	private void populateTable(){
		// Clear the table before populating it
		javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblGestionReservas.getModel();
		model.setRowCount(0); 
		clientInstance.sendMessage("105");
		String raw;
		try {
			raw = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
			raw = raw.substring(3);
		} catch (InterruptedException e) {
			raw = "|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|";
		}
		ArrayList<String> rows = RequestHandler.superArrayReconstructor(raw);
		
		for (String i : rows) {
			ArrayList<String> row = RequestHandler.arrayReconstructor(i);
			if (row.size() == 8) {
				model = (javax.swing.table.DefaultTableModel) tblGestionReservas.getModel();
				model.addRow(new Object[]{row.get(0), row.get(1), row.get(2), row.get(3), row.get(4), row.get(5), row.get(6), row.get(7)});
			} else {
				System.out.println("Error: Row does not contain exactly 8 elements. "+
						"Received: " + row.size() + " elements." + i);
			}
		}
	}

	private void populateTableWithData(String msg){
		// Clear the table before populating it
		javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblGestionReservas.getModel();
		model.setRowCount(0); 
		clientInstance.sendMessage(msg);
		String raw;
		try {
			raw = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
			raw = raw.substring(3);
		} catch (InterruptedException e) {
			raw = "|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|";
		}
		ArrayList<String> rows = RequestHandler.superArrayReconstructor(raw);
		
		for (String i : rows) {
			ArrayList<String> row = RequestHandler.arrayReconstructor(i);
			if (row.size() == 8) {
				model = (javax.swing.table.DefaultTableModel) tblGestionReservas.getModel();
				model.addRow(new Object[]{row.get(0), row.get(1), row.get(2), row.get(3), row.get(4), row.get(5), row.get(6), row.get(7)});
			} else {
				System.out.println("Error: Row does not contain exactly 8 elements. "+
						"Received: " + row.size() + " elements." + i);
			}
		}
	}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrar = new javax.swing.JButton();
        lblFechaInicio = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        lblFechaFin = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        lblPrecioTotal = new javax.swing.JLabel();
        txtPrecioTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGestionReservas = new javax.swing.JTable();
        lblEntregado = new javax.swing.JLabel();
        lblBuscarAgencia = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        txtBuscarAgencia = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        lblBuscarCliente = new javax.swing.JLabel();
        btnConsultarAgencia = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        lblDatosReserva = new javax.swing.JLabel();
        lblBuscarfecha = new javax.swing.JLabel();
        CbxEntrega = new javax.swing.JCheckBox();
        txtBuscarCliente = new javax.swing.JTextField();
        lblDniCliente = new javax.swing.JLabel();
        lblAgencia = new javax.swing.JLabel();
        txtBuscarReserva = new javax.swing.JTextField();
        txtAgencia = new javax.swing.JTextField();
        btnBuscarFecha = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        btnConsultarNombre = new javax.swing.JButton();
        txtDniCliente = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        btnRegistrar.setBackground(new java.awt.Color(8, 156, 12));
        //btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Registrar.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblFechaInicio.setText("Fecha de inicio");

        txtFechaInicio.setToolTipText("");

        lblFechaFin.setText("Fecha fin");

        txtFechaFin.setToolTipText("");

        lblPrecioTotal.setText("Precio total");

        tblGestionReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Reserva", "Automoviles", "Cliente", "Agencia", "Fecha de inicio", "Fecha fin", "Precio total", "Entregado"
            }
        ));
        jScrollPane1.setViewportView(tblGestionReservas);

        lblEntregado.setText("Entregado");

        lblBuscarAgencia.setText("Buscar por agencia");

        btnActualizar.setBackground(new java.awt.Color(8, 156, 12));
        //btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(8, 156, 12));
        //btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/elminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
		btnEliminar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnEliminarActionPerformed(evt);
			}
		});
        lblBuscarCliente.setText("Buscar por cliente");

        btnConsultarAgencia.setBackground(new java.awt.Color(8, 156, 12));
        //btnConsultarAgencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Buscar.png"))); // NOI18N
		btnConsultarAgencia.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnConsultarAgenciaActionPerformed(evt);
			}
		});
		
        btnNuevo.setBackground(new java.awt.Color(8, 156, 12));
        //btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        btnNuevo.setText("Refrescar");
		btnNuevo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnNuevoActionPerformed(evt);
			}
		});

        lblCodigo.setText("Codigo");

        lblDatosReserva.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDatosReserva.setText("DATOS DE LA RESERVA");

        lblBuscarfecha.setText("Buscar por fecha");

        CbxEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxEntregaActionPerformed(evt);
            }
        });

        lblDniCliente.setText("DNI del cliente");

        lblAgencia.setText("Agencia");

        txtAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgenciaActionPerformed(evt);
            }
        });

        btnBuscarFecha.setBackground(new java.awt.Color(8, 156, 12));
        //btnBuscarFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Buscar.png"))); // NOI18N
		btnBuscarFecha.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarFechaActionPerformed(evt);
			}
		});
        txtCodigo.setToolTipText("");
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        btnConsultarNombre.setBackground(new java.awt.Color(8, 156, 12));
        //btnConsultarNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Buscar.png"))); // NOI18N
        btnConsultarNombre.setToolTipText("");
		btnConsultarNombre.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnConsultarNombreActionPerformed(evt);
			}
		});

        txtDniCliente.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDatosReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1070, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEntregado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CbxEntrega)
                                .addGap(451, 451, 451))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblBuscarfecha)
                                        .addComponent(lblBuscarCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnNuevo)
                                            .addComponent(lblBuscarAgencia))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnRegistrar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnActualizar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEliminar))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(txtBuscarAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnConsultarAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(txtBuscarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnBuscarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnConsultarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFechaFin, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAgencia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDniCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrecioTotal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaInicio, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDniCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAgencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtFechaFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(131, 131, 131)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDatosReserva)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAgencia))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDniCliente))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaInicio))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaFin)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecioTotal)
                            .addComponent(txtPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEntregado)
                            .addComponent(CbxEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(btnActualizar)
                            .addComponent(btnEliminar)
                            .addComponent(btnNuevo))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblBuscarCliente)
                                .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblBuscarfecha)
                                .addComponent(txtBuscarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBuscarFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConsultarAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBuscarAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblBuscarAgencia)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void CbxEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxEntregaActionPerformed

    private void txtAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgenciaActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
		String cliente_dni = txtDniCliente.getText();
		String agencia_id = txtAgencia.getText();
		String fecha_inicio = txtFechaInicio.getText();
		String fecha_fin = txtFechaFin.getText();
		String precio_total = txtPrecioTotal.getText();
		String entregado = (CbxEntrega.isSelected()) ? "Si" : "No";

		if (cliente_dni.isEmpty() || agencia_id.isEmpty() || fecha_inicio.isEmpty() || fecha_fin.isEmpty() || precio_total.isEmpty() || entregado.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "Por favor, complete todos los campos antes de registrar.");
		}
		clientInstance.sendMessage("306 |" + cliente_dni + "|" + agencia_id + "|" + fecha_inicio + "|" + fecha_fin + "|" + precio_total + "|" + entregado);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
		String reserva_id = txtCodigo.getText();
		String cliente_dni = txtDniCliente.getText();
		String agencia_id = txtAgencia.getText();
		String fecha_inicio = txtFechaInicio.getText();
		String fecha_fin = txtFechaFin.getText();
		String precio_total = txtPrecioTotal.getText();
		String entregado = (CbxEntrega.isSelected()) ? "Si" : "No";
		if (reserva_id.isEmpty() || cliente_dni.isEmpty() || agencia_id.isEmpty() || fecha_inicio.isEmpty() || fecha_fin.isEmpty() || precio_total.isEmpty() || entregado.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "Por favor, complete todos los campos antes de actualizar.");
		
		}

		clientInstance.sendMessage("312 |" + cliente_dni + "|" + agencia_id + "|" + fecha_inicio + "|" + fecha_fin + "|" + precio_total + "|" + entregado + "|"  + reserva_id + "|" );
		System.out.println("312 |" + cliente_dni + "|" + agencia_id + "|" + fecha_inicio + "|" + fecha_fin + "|" + precio_total + "|" + entregado + "|"  + reserva_id + "|");

		populateTable();
		populateTable();
	}//GEN-LAST:event_btnActualizarActionPerformed

	private void btnConsultarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarNombreActionPerformed
		String nombre = txtBuscarCliente.getText();
		if (nombre.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "Por favor, ingrese un nombre para buscar.");
			return;
		}
		populateTableWithData("114 "+ nombre);
	}//GEN-LAST:event_btnConsultarNombreActionPerformed

	private void btnConsultarAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarAgenciaActionPerformed
		String agencia = txtBuscarAgencia.getText();
		if (agencia.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "Por favor, ingrese una agencia para buscar.");
			return;
		}
		populateTableWithData("116 "+ agencia);
	}//GEN-LAST:event_btnConsultarAgenciaActionPerformed

	private void btnBuscarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFechaActionPerformed
		String fecha = txtBuscarReserva.getText();
		if (fecha.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "Por favor, ingrese una fecha para buscar.");
			return;
		}
		populateTableWithData("115 "+ fecha);
	}//GEN-LAST:event_btnBuscarFechaActionPerformed

	private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
		populateTable();
	}//GEN-LAST:event_btnNuevoActionPerformed

	private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
		String reserva_id = txtCodigo.getText();
		if (reserva_id.isEmpty()) {
			System.out.println("Error: Reserva ID is empty.");
			return;
		}
		clientInstance.sendMessage("405 |" + reserva_id);

		populateTable();
		populateTable();
	}//GEN-LAST:event_btnEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CbxEntrega;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarFecha;
    private javax.swing.JButton btnConsultarAgencia;
    private javax.swing.JButton btnConsultarNombre;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgencia;
    private javax.swing.JLabel lblBuscarAgencia;
    private javax.swing.JLabel lblBuscarCliente;
    private javax.swing.JLabel lblBuscarfecha;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDatosReserva;
    private javax.swing.JLabel lblDniCliente;
    private javax.swing.JLabel lblEntregado;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblPrecioTotal;
    private javax.swing.JTable tblGestionReservas;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtBuscarAgencia;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtBuscarReserva;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtPrecioTotal;
    // End of variables declaration//GEN-END:variables
}
