/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client.gui.presentacion.Empleado;

import client.ClientInstance;
import client.RequestHandler;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author jhose
 */
public class PanGestionClienteEmpleado extends javax.swing.JPanel {

	ClientInstance clientInstance;
    /**
     * Creates new form PanGestionClienteEmpleado
     */
    public PanGestionClienteEmpleado(ClientInstance clientInstance) {
		this.clientInstance = clientInstance;
        initComponents();
		populateTable();
    }

	private void populateTable(){
		// Clear the table before populating it
		javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblGestionClientes.getModel();
		model.setRowCount(0); 
		clientInstance.sendMessage("103");
		String raw;
		try {
			raw = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
			raw = raw.substring(3);
		} catch (InterruptedException e) {
			raw = "|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|";
		}
		ArrayList<String> rows = RequestHandler.superArrayReconstructor(raw);
		
		for (String i : rows) {
			ArrayList<String> row = RequestHandler.arrayReconstructor(i);
			if (row.size() == 5) {
				if (!row.get(0).equals("No Asignado")) {
					model = (javax.swing.table.DefaultTableModel) tblGestionClientes.getModel();
					model.addRow(new Object[]{row.get(0), row.get(1), row.get(2), row.get(3), row.get(4)});
				}
				
			} else {
				System.out.println("Error: Row does not contain exactly 5 elements. "+
						"Received: " + row.size() + " elements." + i);
			}
		}
	}

	private void populateTableWithData(String msg){
		// Clear the table before populating it
		javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblGestionClientes.getModel();
		model.setRowCount(0); 
		clientInstance.sendMessage(msg);
		String raw;
		try {
			raw = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
			raw = raw.substring(3);
		} catch (InterruptedException e) {
			raw = "|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|Error receiving data|";
		}
		ArrayList<String> rows = RequestHandler.superArrayReconstructor(raw);
		
		for (String i : rows) {
			ArrayList<String> row = RequestHandler.arrayReconstructor(i);
			if (row.size() == 5) {
				if (!row.get(0).equals("No Asignado")) {
					model = (javax.swing.table.DefaultTableModel) tblGestionClientes.getModel();
					model.addRow(new Object[]{row.get(0), row.get(1), row.get(2), row.get(3), row.get(4)});
				}
				
			} else {
				System.out.println("Error: Row does not contain exactly 5 elements. "+
						"Received: " + row.size() + " elements." + i);
			}
		}
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSponsor = new javax.swing.JTextField();
        txtBuscarDni = new javax.swing.JTextField();
        lblSponsor = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        btnConsultarDni = new javax.swing.JButton();
        txtDireccion = new javax.swing.JTextField();
        btnConsultarSponsor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGestionClientes = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        lblDatosCliente = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        lblBuscarDNI = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblBuscarCodigo = new javax.swing.JLabel();
        txtBuscarCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txtSponsor.setToolTipText("");

        lblSponsor.setText("DNI del Aval");

        txtTelefono.setToolTipText("");

        txtDNI.setToolTipText("");
        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });

        btnConsultarDni.setBackground(new java.awt.Color(8, 156, 12));
        //btnConsultarDni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Buscar.png"))); // NOI18N
		btnConsultarDni.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnConsultarDniMouseClicked(evt);
			}
		});

        txtDireccion.setToolTipText("");

        btnConsultarSponsor.setBackground(new java.awt.Color(8, 156, 12));
        //btnConsultarSponsor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Buscar.png"))); // NOI18N
		btnConsultarSponsor.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnConsultarSponsorMouseClicked(evt);
			}
		});


        tblGestionClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "DNI", "Nombre", "Direccion", "Telefono", "Sponsor"
            }
        ));
        jScrollPane1.setViewportView(tblGestionClientes);

        btnRegistrar.setBackground(new java.awt.Color(8, 156, 12));
        //btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Registrar.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
		btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnRegistrarMouseClicked(evt);
			}
		});

        lblDatosCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDatosCliente.setText("DATOS DEL CLIENTE");

        btnActualizar.setBackground(new java.awt.Color(8, 156, 12));
        //btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
		btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnActualizarMouseClicked(evt);
			}
		});

        lblCodigo.setText("Codigo");

        lblDNI.setText("DNI");

        btnEliminar.setBackground(new java.awt.Color(8, 156, 12));
        //btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/elminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
		btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnEliminarMouseClicked(evt);
			}
		});

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        lblBuscarDNI.setText("Buscar por dni");

        jButton4.setBackground(new java.awt.Color(8, 156, 12));
        //jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        jButton4.setText("Refrescar");
		jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton4MouseClicked(evt);
			}
		});

        lblNombre.setText("Nombre");

        lblBuscarCodigo.setText("Buscar por sponsor");

        jLabel2.setText("Telefono");

        jLabel1.setText("Direccion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDatosCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBuscarDNI)
                                    .addComponent(jButton4)
                                    .addComponent(lblBuscarCodigo))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnRegistrar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnActualizar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnConsultarSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnConsultarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDNI)
                                    .addComponent(lblNombre)
                                    .addComponent(jLabel1)
                                    .addComponent(lblSponsor)
                                    .addComponent(jLabel2)
                                    .addComponent(lblCodigo))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtNombre)
                                    .addComponent(txtDNI)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtSponsor)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDatosCliente)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDNI)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSponsor))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(btnActualizar)
                            .addComponent(btnEliminar)
                            .addComponent(jButton4))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblBuscarCodigo))
                                    .addComponent(btnConsultarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConsultarSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblBuscarDNI))))
                .addGap(134, 134, 134))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed



	private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked	
		String dni = txtDNI.getText();
		String nombre = txtNombre.getText();
		String direccion = txtDireccion.getText();
		String telefono = txtTelefono.getText();
		String sponsor = txtSponsor.getText();

		if (dni.isEmpty() || nombre.isEmpty() || direccion.isEmpty() || telefono.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "All fields must be filled out.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
			System.out.println("Error: All fields must be filled out.");
			return;
		}

		if (sponsor.isEmpty()) {
			sponsor = "6"; // Default value if sponsor is not provided
			System.out.println("Sponsor not provided, setting to 'N/A'.");
		}


		clientInstance.sendMessage("304 " + "|" + dni + "|" + nombre + "|" + direccion + "|" + telefono + "|" + sponsor);

		String response;
		try {
			response = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
		} catch (InterruptedException e) {
			response ="801" + e.getMessage();
		}
		if (response.equals("800")) {
			System.out.println("Client registered successfully.");
			populateTable();
		} else {
			System.out.println("Error registering : " + response);
		}
	}//GEN-LAST:event_btnRegistrarMouseClicked

	private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
		populateTable();
	}//GEN-LAST:event_jButton4MouseClicked

	private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
		String agencia = txtDNI.getText();

		if (agencia.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "All fields must be filled out.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
			System.out.println("Error: All fields must be filled out.");
			return;
		}
		clientInstance.sendMessage("404 |" + agencia+"|");

		populateTable();
	}

	private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
		String dni = txtDNI.getText();
		String nombre = txtNombre.getText();
		String direccion = txtDireccion.getText();
		String telefono = txtTelefono.getText();
		String sponsor = txtSponsor.getText();

		if (dni.isEmpty() || nombre.isEmpty() || direccion.isEmpty() || telefono.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "All fields must be filled out.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
			System.out.println("Error: All fields must be filled out.");
			return;
		}

		if (sponsor.isEmpty()) {
			sponsor = "6"; // Default value if sponsor is not provided
			System.out.println("Sponsor not provided, setting to 'N/A'.");
			clientInstance.sendMessage("311 "+ "|" + nombre + "|" + direccion + "|" + telefono + "|" + sponsor + "|" + dni );

		}

		else{
			clientInstance.sendMessage("311 "+ "|" + nombre + "|" + direccion + "|" + telefono + "|" + sponsor + "|" + dni );

		}
		String response;
		try {
			response = clientInstance.receiveMessage(2, TimeUnit.SECONDS);
		} catch (InterruptedException e) {
			response = "801" + e.getMessage();
		}
		if (response.equals("800")) {
			System.out.println("Agency updated successfully.");
			populateTable();
		} else {
			System.out.println("Error updating agency: " + response);
		}
	}//GEN-LAST:event_btnActualizarMouseClicked

	private void btnConsultarDniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarDniMouseClicked
		String sponsor = txtBuscarCodigo.getText();
		if (sponsor.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "Please enter a Sponsor to search.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
			System.out.println("Error: Please enter a Sponsor to search.");
			return;
		}
		populateTableWithData("113 " + "|" + sponsor);
		System.out.println("Searching for clients with Sponsor: " + sponsor);
	}//GEN-LAST:event_btnConsultarDniMouseClicked
	private void btnConsultarSponsorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarSponsorMouseClicked
		String dni = txtBuscarDni.getText();
		if (dni.isEmpty()) {
			new javax.swing.JOptionPane().showMessageDialog(this, "Please enter a DNI to search.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
			System.out.println("Error: Please enter a DNI to search.");
			return;
		}
		populateTableWithData("112 " + "|" + dni);
		System.out.println("Searching for client with DNI: " + dni);
		
	}//GEN-LAST:event_btnConsultarSponsorMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultarDni;
    private javax.swing.JButton btnConsultarSponsor;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarCodigo;
    private javax.swing.JLabel lblBuscarDNI;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDatosCliente;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSponsor;
    private javax.swing.JTable tblGestionClientes;
    private javax.swing.JTextField txtBuscarCodigo;
    private javax.swing.JTextField txtBuscarDni;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtSponsor;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
